POST http://localhost:3002/api/auth/login
content-type: application/json

{
    "credentials": { 
        "email": "ericmoura511@gmail.com",
        "password": "ericaolanches12"
    },
    "type": "teacher"
}

###

PUT http://localhost:3002/api/teacher/6
content-type: application/json

{
    "email": "ericmoura511@gmail.com"
}

###

POST http://localhost:3002/api/teacher/password-reset
content-type: application/json

{
    "email": "ericmoura511@gmail.com"
}

###

POST http://localhost:3002/api/manager/password-reset/6/4ff0547acf379f17f9475e9d6e2cd30d27ea27138b7ffe19489ac2851ef9744e
Content-Type: application/json

{
    "password": "aaaaaaaaaaaaaaa"
}