POST http://localhost:3002/api/auth/login
content-type: application/json

{
    "credentials": { 
        "email": "ericmoura511@gmail.com",
        "password": "ericaolanches12"
    },
    "type": "teacher"
}

###

PUT http://localhost:3002/api/teacher/6
content-type: application/json

{
    "email": "ericmoura511@gmail.com"
}

###

POST http://localhost:3002/api/teacher/password-reset
content-type: application/json

{
    "email": "ericmoura511@gmail.com"
}

###

POST http://localhost:3002/api/teacher/password-reset/6/3a567e8578ca0ae6ca4e5858c0e21e8462ba77600e7a6cf252249c1a5b50c89a
Content-Type: application/json

{
    "password": "ericaolanches12"
}