export {default as managerRouter} from "./manager";
export {default as materialRouter} from "./material";
export {default as modalityRouter} from "./modality";
export {default as teacherRouter} from "./teacher";
export {default as athleteRouter} from "./athlete";
export {default as athleteUserBaseRouter} from "./userBase";
export {default as authRouter} from "./auth"
export {default as enrollmentRouter} from "./enrollment"
export {default as absencesRouter} from "./absences"
export {default as registerRouter} from "./register"
export {default as authMiddlewareRouter} from "./auth-middleware"
