import { MigrationInterface, QueryRunner } from "typeorm";

export class PopulandoAtendimentos1749136523178 implements MigrationInterface {
    name = 'PopulandoAtendimentos1749136523178'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "address" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "state" text NOT NULL, "city" text NOT NULL, "neighborhood" text NOT NULL, "street" text NOT NULL, "number" integer NOT NULL, "complement" text NOT NULL, "references" text NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "user-base" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_0dfb99b20ad3c8c6b1f16eae4db" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "token" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "token" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "teacherId" integer)`);
        await queryRunner.query(`CREATE TABLE "teacher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "about" text NOT NULL, "addressId" integer, "modalityId" integer, CONSTRAINT "UQ_00634394dce7677d531749ed8e8" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "enrollment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "active" boolean NOT NULL DEFAULT (0), "approved" boolean NOT NULL DEFAULT (0), "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP), "athleteId" integer, "modalityId" integer)`);
        await queryRunner.query(`CREATE TABLE "modality" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "days_of_week" text NOT NULL, "start_time" time NOT NULL, "end_time" time NOT NULL, "class_locations" text NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "atendiment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "present" boolean NOT NULL, "description" text, "modalityId" integer, "athleteId" integer)`);
        await queryRunner.query(`CREATE TABLE "athlete" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "father_name" text DEFAULT ('Nenhum nome informado'), "father_phone" text, "father_cpf" text, "father_email" text, "mother_name" text DEFAULT ('Nenhum nome informado'), "mother_phone" text, "mother_cpf" text, "mother_email" text, "responsible_person_name" text DEFAULT ('Nenhum responsável informado'), "responsible_person_email" text, "responsible_person_cpf" text, "blood_type" text DEFAULT ('Nenhum tipo sanguíneo informado'), "photo_url_cpf_front" text, "photo_url_cpf_back" text, "allergy" text DEFAULT ('Nenhuma alergia informada'), "addressId" integer, CONSTRAINT "UQ_6b605cd9ed2fc11b50677fc8f2d" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "manager" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_ee8fba4edb704ce2465753a2edd" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "material" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "description" text DEFAULT ('Sem descrição'), "quantity" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`CREATE TABLE "documentation" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" text NOT NULL, "description" text NOT NULL, "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`CREATE TABLE "release" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" text NOT NULL, "content" text NOT NULL, "priority" varchar CHECK( "priority" IN ('HIGH','LOW') ) NOT NULL DEFAULT ('LOW'), "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`CREATE TABLE "temporary_user-base" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_0dfb99b20ad3c8c6b1f16eae4db" UNIQUE ("email"), CONSTRAINT "FK_ab73ab19e736c37c4a1502d9924" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user-base"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "user-base"`);
        await queryRunner.query(`DROP TABLE "user-base"`);
        await queryRunner.query(`ALTER TABLE "temporary_user-base" RENAME TO "user-base"`);
        await queryRunner.query(`CREATE TABLE "temporary_token" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "token" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "teacherId" integer, CONSTRAINT "FK_04ccdcb61d5d2cb72312ab515e2" FOREIGN KEY ("teacherId") REFERENCES "teacher" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_token"("id", "token", "createdAt", "teacherId") SELECT "id", "token", "createdAt", "teacherId" FROM "token"`);
        await queryRunner.query(`DROP TABLE "token"`);
        await queryRunner.query(`ALTER TABLE "temporary_token" RENAME TO "token"`);
        await queryRunner.query(`CREATE TABLE "temporary_teacher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "about" text NOT NULL, "addressId" integer, "modalityId" integer, CONSTRAINT "UQ_00634394dce7677d531749ed8e8" UNIQUE ("email"), CONSTRAINT "FK_eb4a42b66ce9356dc776e227652" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_316b0a548186c8ff19da65676f9" FOREIGN KEY ("modalityId") REFERENCES "modality" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_teacher"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId" FROM "teacher"`);
        await queryRunner.query(`DROP TABLE "teacher"`);
        await queryRunner.query(`ALTER TABLE "temporary_teacher" RENAME TO "teacher"`);
        await queryRunner.query(`CREATE TABLE "temporary_enrollment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "active" boolean NOT NULL DEFAULT (0), "approved" boolean NOT NULL DEFAULT (0), "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP), "athleteId" integer, "modalityId" integer, CONSTRAINT "FK_9da60bd721aae7b35c89b448751" FOREIGN KEY ("athleteId") REFERENCES "athlete" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_df014b705a2c5dff9da9ba54c54" FOREIGN KEY ("modalityId") REFERENCES "modality" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_enrollment"("id", "active", "approved", "created_at", "updated_at", "athleteId", "modalityId") SELECT "id", "active", "approved", "created_at", "updated_at", "athleteId", "modalityId" FROM "enrollment"`);
        await queryRunner.query(`DROP TABLE "enrollment"`);
        await queryRunner.query(`ALTER TABLE "temporary_enrollment" RENAME TO "enrollment"`);
        await queryRunner.query(`CREATE TABLE "temporary_atendiment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "present" boolean NOT NULL, "description" text, "modalityId" integer, "athleteId" integer, CONSTRAINT "FK_94559c147b79dc19928622c55a3" FOREIGN KEY ("modalityId") REFERENCES "modality" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_549c5e59022f9902b94afefd420" FOREIGN KEY ("athleteId") REFERENCES "athlete" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_atendiment"("id", "created_at", "present", "description", "modalityId", "athleteId") SELECT "id", "created_at", "present", "description", "modalityId", "athleteId" FROM "atendiment"`);
        await queryRunner.query(`DROP TABLE "atendiment"`);
        await queryRunner.query(`ALTER TABLE "temporary_atendiment" RENAME TO "atendiment"`);
        await queryRunner.query(`CREATE TABLE "temporary_athlete" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "father_name" text DEFAULT ('Nenhum nome informado'), "father_phone" text, "father_cpf" text, "father_email" text, "mother_name" text DEFAULT ('Nenhum nome informado'), "mother_phone" text, "mother_cpf" text, "mother_email" text, "responsible_person_name" text DEFAULT ('Nenhum responsável informado'), "responsible_person_email" text, "responsible_person_cpf" text, "blood_type" text DEFAULT ('Nenhum tipo sanguíneo informado'), "photo_url_cpf_front" text, "photo_url_cpf_back" text, "allergy" text DEFAULT ('Nenhuma alergia informada'), "addressId" integer, CONSTRAINT "UQ_6b605cd9ed2fc11b50677fc8f2d" UNIQUE ("email"), CONSTRAINT "FK_61d2ccc7855bb7c86d8f575c6ba" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_athlete"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId" FROM "athlete"`);
        await queryRunner.query(`DROP TABLE "athlete"`);
        await queryRunner.query(`ALTER TABLE "temporary_athlete" RENAME TO "athlete"`);
        await queryRunner.query(`CREATE TABLE "temporary_manager" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_ee8fba4edb704ce2465753a2edd" UNIQUE ("email"), CONSTRAINT "FK_a0337c855fa0d66e7404170d4fc" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_manager"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "manager"`);
        await queryRunner.query(`DROP TABLE "manager"`);
        await queryRunner.query(`ALTER TABLE "temporary_manager" RENAME TO "manager"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "manager" RENAME TO "temporary_manager"`);
        await queryRunner.query(`CREATE TABLE "manager" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_ee8fba4edb704ce2465753a2edd" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "manager"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "temporary_manager"`);
        await queryRunner.query(`DROP TABLE "temporary_manager"`);
        await queryRunner.query(`ALTER TABLE "athlete" RENAME TO "temporary_athlete"`);
        await queryRunner.query(`CREATE TABLE "athlete" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "father_name" text DEFAULT ('Nenhum nome informado'), "father_phone" text, "father_cpf" text, "father_email" text, "mother_name" text DEFAULT ('Nenhum nome informado'), "mother_phone" text, "mother_cpf" text, "mother_email" text, "responsible_person_name" text DEFAULT ('Nenhum responsável informado'), "responsible_person_email" text, "responsible_person_cpf" text, "blood_type" text DEFAULT ('Nenhum tipo sanguíneo informado'), "photo_url_cpf_front" text, "photo_url_cpf_back" text, "allergy" text DEFAULT ('Nenhuma alergia informada'), "addressId" integer, CONSTRAINT "UQ_6b605cd9ed2fc11b50677fc8f2d" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "athlete"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId" FROM "temporary_athlete"`);
        await queryRunner.query(`DROP TABLE "temporary_athlete"`);
        await queryRunner.query(`ALTER TABLE "atendiment" RENAME TO "temporary_atendiment"`);
        await queryRunner.query(`CREATE TABLE "atendiment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "present" boolean NOT NULL, "description" text, "modalityId" integer, "athleteId" integer)`);
        await queryRunner.query(`INSERT INTO "atendiment"("id", "created_at", "present", "description", "modalityId", "athleteId") SELECT "id", "created_at", "present", "description", "modalityId", "athleteId" FROM "temporary_atendiment"`);
        await queryRunner.query(`DROP TABLE "temporary_atendiment"`);
        await queryRunner.query(`ALTER TABLE "enrollment" RENAME TO "temporary_enrollment"`);
        await queryRunner.query(`CREATE TABLE "enrollment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "active" boolean NOT NULL DEFAULT (0), "approved" boolean NOT NULL DEFAULT (0), "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP), "athleteId" integer, "modalityId" integer)`);
        await queryRunner.query(`INSERT INTO "enrollment"("id", "active", "approved", "created_at", "updated_at", "athleteId", "modalityId") SELECT "id", "active", "approved", "created_at", "updated_at", "athleteId", "modalityId" FROM "temporary_enrollment"`);
        await queryRunner.query(`DROP TABLE "temporary_enrollment"`);
        await queryRunner.query(`ALTER TABLE "teacher" RENAME TO "temporary_teacher"`);
        await queryRunner.query(`CREATE TABLE "teacher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "about" text NOT NULL, "addressId" integer, "modalityId" integer, CONSTRAINT "UQ_00634394dce7677d531749ed8e8" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "teacher"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId" FROM "temporary_teacher"`);
        await queryRunner.query(`DROP TABLE "temporary_teacher"`);
        await queryRunner.query(`ALTER TABLE "token" RENAME TO "temporary_token"`);
        await queryRunner.query(`CREATE TABLE "token" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "token" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "teacherId" integer)`);
        await queryRunner.query(`INSERT INTO "token"("id", "token", "createdAt", "teacherId") SELECT "id", "token", "createdAt", "teacherId" FROM "temporary_token"`);
        await queryRunner.query(`DROP TABLE "temporary_token"`);
        await queryRunner.query(`ALTER TABLE "user-base" RENAME TO "temporary_user-base"`);
        await queryRunner.query(`CREATE TABLE "user-base" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_0dfb99b20ad3c8c6b1f16eae4db" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "user-base"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "temporary_user-base"`);
        await queryRunner.query(`DROP TABLE "temporary_user-base"`);
        await queryRunner.query(`DROP TABLE "release"`);
        await queryRunner.query(`DROP TABLE "documentation"`);
        await queryRunner.query(`DROP TABLE "material"`);
        await queryRunner.query(`DROP TABLE "manager"`);
        await queryRunner.query(`DROP TABLE "athlete"`);
        await queryRunner.query(`DROP TABLE "atendiment"`);
        await queryRunner.query(`DROP TABLE "modality"`);
        await queryRunner.query(`DROP TABLE "enrollment"`);
        await queryRunner.query(`DROP TABLE "teacher"`);
        await queryRunner.query(`DROP TABLE "token"`);
        await queryRunner.query(`DROP TABLE "user-base"`);
        await queryRunner.query(`DROP TABLE "address"`);
    }

}
