import { MigrationInterface, QueryRunner } from "typeorm";

export class PopulandoAtendimentos1749221636433 implements MigrationInterface {
    name = 'PopulandoAtendimentos1749221636433'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_user-base" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_0dfb99b20ad3c8c6b1f16eae4db" UNIQUE ("email"), CONSTRAINT "FK_ab73ab19e736c37c4a1502d9924" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user-base"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "user-base"`);
        await queryRunner.query(`DROP TABLE "user-base"`);
        await queryRunner.query(`ALTER TABLE "temporary_user-base" RENAME TO "user-base"`);
        await queryRunner.query(`CREATE TABLE "temporary_teacher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "about" text NOT NULL, "addressId" integer, "modalityId" integer, CONSTRAINT "UQ_00634394dce7677d531749ed8e8" UNIQUE ("email"), CONSTRAINT "FK_316b0a548186c8ff19da65676f9" FOREIGN KEY ("modalityId") REFERENCES "modality" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_eb4a42b66ce9356dc776e227652" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_teacher"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId" FROM "teacher"`);
        await queryRunner.query(`DROP TABLE "teacher"`);
        await queryRunner.query(`ALTER TABLE "temporary_teacher" RENAME TO "teacher"`);
        await queryRunner.query(`CREATE TABLE "temporary_athlete" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "father_name" text DEFAULT ('Nenhum nome informado'), "father_phone" text, "father_cpf" text, "father_email" text, "mother_name" text DEFAULT ('Nenhum nome informado'), "mother_phone" text, "mother_cpf" text, "mother_email" text, "responsible_person_name" text DEFAULT ('Nenhum responsável informado'), "responsible_person_email" text, "responsible_person_cpf" text, "blood_type" text DEFAULT ('Nenhum tipo sanguíneo informado'), "photo_url_cpf_front" text, "photo_url_cpf_back" text, "allergy" text DEFAULT ('Nenhuma alergia informada'), "addressId" integer, CONSTRAINT "UQ_6b605cd9ed2fc11b50677fc8f2d" UNIQUE ("email"), CONSTRAINT "FK_61d2ccc7855bb7c86d8f575c6ba" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_athlete"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId" FROM "athlete"`);
        await queryRunner.query(`DROP TABLE "athlete"`);
        await queryRunner.query(`ALTER TABLE "temporary_athlete" RENAME TO "athlete"`);
        await queryRunner.query(`CREATE TABLE "temporary_manager" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_ee8fba4edb704ce2465753a2edd" UNIQUE ("email"), CONSTRAINT "FK_a0337c855fa0d66e7404170d4fc" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_manager"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "manager"`);
        await queryRunner.query(`DROP TABLE "manager"`);
        await queryRunner.query(`ALTER TABLE "temporary_manager" RENAME TO "manager"`);
        await queryRunner.query(`CREATE TABLE "temporary_release" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" text NOT NULL, "content" text NOT NULL, "priority" varchar CHECK( "priority" IN ('HIGH','LOW') ) NOT NULL DEFAULT ('LOW'), "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "temporary_release"("id", "title", "content", "priority", "created_at") SELECT "id", "title", "content", "priority", "created_at" FROM "release"`);
        await queryRunner.query(`DROP TABLE "release"`);
        await queryRunner.query(`ALTER TABLE "temporary_release" RENAME TO "release"`);
        await queryRunner.query(`CREATE TABLE "temporary_modality" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "days_of_week" text NOT NULL, "start_time" time NOT NULL, "end_time" time NOT NULL, "class_locations" text NOT NULL, "ativo" boolean NOT NULL DEFAULT (1))`);
        await queryRunner.query(`INSERT INTO "temporary_modality"("id", "name", "description", "days_of_week", "start_time", "end_time", "class_locations") SELECT "id", "name", "description", "days_of_week", "start_time", "end_time", "class_locations" FROM "modality"`);
        await queryRunner.query(`DROP TABLE "modality"`);
        await queryRunner.query(`ALTER TABLE "temporary_modality" RENAME TO "modality"`);
        await queryRunner.query(`CREATE TABLE "temporary_user-base" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_0dfb99b20ad3c8c6b1f16eae4db" UNIQUE ("email"), CONSTRAINT "FK_ab73ab19e736c37c4a1502d9924" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user-base"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "user-base"`);
        await queryRunner.query(`DROP TABLE "user-base"`);
        await queryRunner.query(`ALTER TABLE "temporary_user-base" RENAME TO "user-base"`);
        await queryRunner.query(`CREATE TABLE "temporary_teacher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "about" text NOT NULL, "addressId" integer, "modalityId" integer, CONSTRAINT "UQ_00634394dce7677d531749ed8e8" UNIQUE ("email"), CONSTRAINT "FK_316b0a548186c8ff19da65676f9" FOREIGN KEY ("modalityId") REFERENCES "modality" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_eb4a42b66ce9356dc776e227652" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_teacher"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId" FROM "teacher"`);
        await queryRunner.query(`DROP TABLE "teacher"`);
        await queryRunner.query(`ALTER TABLE "temporary_teacher" RENAME TO "teacher"`);
        await queryRunner.query(`CREATE TABLE "temporary_athlete" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "father_name" text DEFAULT ('Nenhum nome informado'), "father_phone" text, "father_cpf" text, "father_email" text, "mother_name" text DEFAULT ('Nenhum nome informado'), "mother_phone" text, "mother_cpf" text, "mother_email" text, "responsible_person_name" text DEFAULT ('Nenhum responsável informado'), "responsible_person_email" text, "responsible_person_cpf" text, "blood_type" text DEFAULT ('Nenhum tipo sanguíneo informado'), "photo_url_cpf_front" text, "photo_url_cpf_back" text, "allergy" text DEFAULT ('Nenhuma alergia informada'), "addressId" integer, CONSTRAINT "UQ_6b605cd9ed2fc11b50677fc8f2d" UNIQUE ("email"), CONSTRAINT "FK_61d2ccc7855bb7c86d8f575c6ba" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_athlete"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId" FROM "athlete"`);
        await queryRunner.query(`DROP TABLE "athlete"`);
        await queryRunner.query(`ALTER TABLE "temporary_athlete" RENAME TO "athlete"`);
        await queryRunner.query(`CREATE TABLE "temporary_manager" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_ee8fba4edb704ce2465753a2edd" UNIQUE ("email"), CONSTRAINT "FK_a0337c855fa0d66e7404170d4fc" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_manager"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "manager"`);
        await queryRunner.query(`DROP TABLE "manager"`);
        await queryRunner.query(`ALTER TABLE "temporary_manager" RENAME TO "manager"`);
        await queryRunner.query(`CREATE TABLE "temporary_release" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" text NOT NULL, "content" text NOT NULL, "priority" varchar CHECK( "priority" IN ('HIGH','LOW') ) NOT NULL DEFAULT ('LOW'), "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "temporary_release"("id", "title", "content", "priority", "created_at") SELECT "id", "title", "content", "priority", "created_at" FROM "release"`);
        await queryRunner.query(`DROP TABLE "release"`);
        await queryRunner.query(`ALTER TABLE "temporary_release" RENAME TO "release"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "release" RENAME TO "temporary_release"`);
        await queryRunner.query(`CREATE TABLE "release" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" text NOT NULL, "content" text NOT NULL, "priority" varchar CHECK( "priority" IN ('HIGH','LOW') ) NOT NULL DEFAULT ('LOW'), "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "release"("id", "title", "content", "priority", "created_at") SELECT "id", "title", "content", "priority", "created_at" FROM "temporary_release"`);
        await queryRunner.query(`DROP TABLE "temporary_release"`);
        await queryRunner.query(`ALTER TABLE "manager" RENAME TO "temporary_manager"`);
        await queryRunner.query(`CREATE TABLE "manager" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_ee8fba4edb704ce2465753a2edd" UNIQUE ("email"), CONSTRAINT "FK_a0337c855fa0d66e7404170d4fc" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "manager"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "temporary_manager"`);
        await queryRunner.query(`DROP TABLE "temporary_manager"`);
        await queryRunner.query(`ALTER TABLE "athlete" RENAME TO "temporary_athlete"`);
        await queryRunner.query(`CREATE TABLE "athlete" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "father_name" text DEFAULT ('Nenhum nome informado'), "father_phone" text, "father_cpf" text, "father_email" text, "mother_name" text DEFAULT ('Nenhum nome informado'), "mother_phone" text, "mother_cpf" text, "mother_email" text, "responsible_person_name" text DEFAULT ('Nenhum responsável informado'), "responsible_person_email" text, "responsible_person_cpf" text, "blood_type" text DEFAULT ('Nenhum tipo sanguíneo informado'), "photo_url_cpf_front" text, "photo_url_cpf_back" text, "allergy" text DEFAULT ('Nenhuma alergia informada'), "addressId" integer, CONSTRAINT "UQ_6b605cd9ed2fc11b50677fc8f2d" UNIQUE ("email"), CONSTRAINT "FK_61d2ccc7855bb7c86d8f575c6ba" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "athlete"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId" FROM "temporary_athlete"`);
        await queryRunner.query(`DROP TABLE "temporary_athlete"`);
        await queryRunner.query(`ALTER TABLE "teacher" RENAME TO "temporary_teacher"`);
        await queryRunner.query(`CREATE TABLE "teacher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "about" text NOT NULL, "addressId" integer, "modalityId" integer, CONSTRAINT "UQ_00634394dce7677d531749ed8e8" UNIQUE ("email"), CONSTRAINT "FK_316b0a548186c8ff19da65676f9" FOREIGN KEY ("modalityId") REFERENCES "modality" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_eb4a42b66ce9356dc776e227652" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "teacher"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId" FROM "temporary_teacher"`);
        await queryRunner.query(`DROP TABLE "temporary_teacher"`);
        await queryRunner.query(`ALTER TABLE "user-base" RENAME TO "temporary_user-base"`);
        await queryRunner.query(`CREATE TABLE "user-base" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_0dfb99b20ad3c8c6b1f16eae4db" UNIQUE ("email"), CONSTRAINT "FK_ab73ab19e736c37c4a1502d9924" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "user-base"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "temporary_user-base"`);
        await queryRunner.query(`DROP TABLE "temporary_user-base"`);
        await queryRunner.query(`ALTER TABLE "modality" RENAME TO "temporary_modality"`);
        await queryRunner.query(`CREATE TABLE "modality" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "days_of_week" text NOT NULL, "start_time" time NOT NULL, "end_time" time NOT NULL, "class_locations" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "modality"("id", "name", "description", "days_of_week", "start_time", "end_time", "class_locations") SELECT "id", "name", "description", "days_of_week", "start_time", "end_time", "class_locations" FROM "temporary_modality"`);
        await queryRunner.query(`DROP TABLE "temporary_modality"`);
        await queryRunner.query(`ALTER TABLE "release" RENAME TO "temporary_release"`);
        await queryRunner.query(`CREATE TABLE "release" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" text NOT NULL, "content" text NOT NULL, "priority" varchar CHECK( "priority" IN ('HIGH','LOW') ) NOT NULL DEFAULT ('LOW'), "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "release"("id", "title", "content", "priority", "created_at") SELECT "id", "title", "content", "priority", "created_at" FROM "temporary_release"`);
        await queryRunner.query(`DROP TABLE "temporary_release"`);
        await queryRunner.query(`ALTER TABLE "manager" RENAME TO "temporary_manager"`);
        await queryRunner.query(`CREATE TABLE "manager" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_ee8fba4edb704ce2465753a2edd" UNIQUE ("email"), CONSTRAINT "FK_a0337c855fa0d66e7404170d4fc" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "manager"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "temporary_manager"`);
        await queryRunner.query(`DROP TABLE "temporary_manager"`);
        await queryRunner.query(`ALTER TABLE "athlete" RENAME TO "temporary_athlete"`);
        await queryRunner.query(`CREATE TABLE "athlete" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "father_name" text DEFAULT ('Nenhum nome informado'), "father_phone" text, "father_cpf" text, "father_email" text, "mother_name" text DEFAULT ('Nenhum nome informado'), "mother_phone" text, "mother_cpf" text, "mother_email" text, "responsible_person_name" text DEFAULT ('Nenhum responsável informado'), "responsible_person_email" text, "responsible_person_cpf" text, "blood_type" text DEFAULT ('Nenhum tipo sanguíneo informado'), "photo_url_cpf_front" text, "photo_url_cpf_back" text, "allergy" text DEFAULT ('Nenhuma alergia informada'), "addressId" integer, CONSTRAINT "UQ_6b605cd9ed2fc11b50677fc8f2d" UNIQUE ("email"), CONSTRAINT "FK_61d2ccc7855bb7c86d8f575c6ba" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "athlete"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "father_name", "father_phone", "father_cpf", "father_email", "mother_name", "mother_phone", "mother_cpf", "mother_email", "responsible_person_name", "responsible_person_email", "responsible_person_cpf", "blood_type", "photo_url_cpf_front", "photo_url_cpf_back", "allergy", "addressId" FROM "temporary_athlete"`);
        await queryRunner.query(`DROP TABLE "temporary_athlete"`);
        await queryRunner.query(`ALTER TABLE "teacher" RENAME TO "temporary_teacher"`);
        await queryRunner.query(`CREATE TABLE "teacher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "about" text NOT NULL, "addressId" integer, "modalityId" integer, CONSTRAINT "UQ_00634394dce7677d531749ed8e8" UNIQUE ("email"), CONSTRAINT "FK_316b0a548186c8ff19da65676f9" FOREIGN KEY ("modalityId") REFERENCES "modality" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_eb4a42b66ce9356dc776e227652" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "teacher"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "about", "addressId", "modalityId" FROM "temporary_teacher"`);
        await queryRunner.query(`DROP TABLE "temporary_teacher"`);
        await queryRunner.query(`ALTER TABLE "user-base" RENAME TO "temporary_user-base"`);
        await queryRunner.query(`CREATE TABLE "user-base" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "cpf" text(11) NOT NULL, "rg" text, "birthday" text NOT NULL, "phone" text NOT NULL, "photo_url" text, "email" text, "role" varchar CHECK( "role" IN ('1','2','3') ) NOT NULL, "addressId" integer, CONSTRAINT "UQ_0dfb99b20ad3c8c6b1f16eae4db" UNIQUE ("email"), CONSTRAINT "FK_ab73ab19e736c37c4a1502d9924" FOREIGN KEY ("addressId") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "user-base"("id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId") SELECT "id", "name", "password", "cpf", "rg", "birthday", "phone", "photo_url", "email", "role", "addressId" FROM "temporary_user-base"`);
        await queryRunner.query(`DROP TABLE "temporary_user-base"`);
    }

}
